
title: Dennis Lee
description: A Red Hatter
url: http://dennisleetw.github.io/
permalink: ':title/'

markdown: kramdown
baseurl: ""
#full-version: "http://webjeda.com/karna-full/"

sass:
    style: compressed

footer-links:
  dribbble:
  email: dennislee22@gmail.com
  facebook:
  flickr:
  github: dennisleetw
  instagram:
  linkedin: dennis-lee-030749a
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
#analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
